matrix:
  include:
    - language: node_js
      node_js:
        - "10.9"
      cache:
        directories:
          - rss-analyzer-ui/node_modules
      addons:
      sudo: required
      apt:
        sources:
          - google-chrome
        packages:
          - google-chrome-stable
          - google-chrome-beta
      before_install:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      before_script:
        - "sudo chown root /opt/google/chrome/chrome-sandbox"
        - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
        - npm config set strict-ssl false
        - npm config set registry https://registry.npmjs.org/
        - npm install -g @angular/cli
        - npm install -g karma
        - "cd rss-analyzer-ui"
        - npm install
      script:
        - ng build
        - ng test --watch=false
      after_script:
        - "kill $(jobs -p)"
    - language: java
      jdk: openjdk8
      cache:
        directories:
          - $HOME/.m2
      script:
        - mvn test
notifications:
  email: false